mode: "dev"
serviceName: "avito-spring"
secret: "DYHlaJpPiZ"

server:
  port: 8080
  grpc_port: 3000
  scheme: "http"
  domain: "localhost"

db:
  host: "db"
  port: 5432
  user: "app_owner"
  password: "app_password"
  database: "app_db"

prometheus:
  port: 9000
