mode: "dev"
serviceName: "svc-name"
secret: "DYHlaJpPiZ"

server:
  port: 8080
  grpc_port: 3000
  scheme: "http"
  domain: "localhost"

db:
  host: "localhost"
  port: 5432
  user: "app_owner"
  password: "app_password"
  database: "app_db_test"

prometheus:
  port: 9000